name: Build Binary

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  linux:
    name: Build on Linux
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Clone Repository
      with: 
        submodules: recursive
      
    - name: Preparation
      run: |
        sudo apt-get update -y
        sudo apt-get install cmake -y
        mkdir build
        
    - name: Make
      working-directory: ./build
      run: |
        cmake ..
        make -j2
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: linux
        path: ./build/decoder
  
  windows:
    name: Build on Windows
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
      name: Clone Repository
      with: 
        submodules: recursive
      
    - name: Preparation
      run: |
        mkdir build
        
    - name: Make
      working-directory: ./build
      run: |
        cmake -G "NMake Makefiles" .. -DCMAKE_BUILD_TYPE=Release
        nmake
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: windows
        path: ./build/
